export const DtSignIn = '/api/doctor/signIn'
export const DtCheckAuth = '/api/doctor/checkAuth' 
export const DtSignOut = '/api/doctor/signOut'
export const PatientRegister = '/api/patient/register'
export const PatientCancel = '/api/patient/cancel'
export const PatientInfo = '/api/patient/info'
export const PatientEdit = '/api/patient/edit'
export const PatientList  = '/api/user/list'
export const PatientRemove  = '/api/user/remove'
export const WkTimeNearest = '/api/patient/nearShift'
export const WkTimeListAll = '/api/time/list'
export const WkDayCreateShift = '/api/time/shift/create' 
export const CurrentAmount = '/api/patient/current'
export const BookingReset = '/api/user/removeAll'
export const BookingTreated = '/api/user/remove'

